import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Sidebar = dynamic(() => import("@/components/Sidebar"));
const Navbar = dynamic(() => import("@/components/Navbar"));

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-gray-200`}>
                <div className="flex p-5">
                    <div className="hidden md:block ">
                        <Sidebar />
                    </div>
                    <div className="lg:ml-80">
                        <Navbar />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
